/*
  Harder version of [013] generated by Claude AI.
  Write a program that:

  - Takes a sorted array as input
  - Takes multiple values to be inserted (also given in sorted order)
  - Inserts all values while maintaining sorted order
  - Constraint: You must do this in O(n + m) time, where n = original array size, m = number of values to insert
  
  This means you can only make ONE pass through the data. No nested loops allowed!
*/

#include <stdio.h>

int main(void)
{
    int array[100], insert_array[100], result[100];
    int val_insert_count, arr_size, i = 0, j = 0, k = 0;
    
    printf("Enter array size: ");
    scanf("%d", &arr_size);
    
    printf("Enter elements (in ascending order):\n");
    for (i = 0; i < arr_size; i++)
    {
        printf("Enter element[%d]: ", i);
        scanf("%d", &array[i]);
    }
    
    printf("How many elements will you insert?: ");
    scanf("%d", &val_insert_count);
    
    printf("Enter elements to insert (in ascending order):\n");
    for (i = 0; i < val_insert_count; i++)
    {
        printf("Enter value[%d]: ", i);
        scanf("%d", &insert_array[i]);
    }
    
    // Reset indices for merge
    i = 0;
    j = 0;
    k = 0;
    
    // Merge both arrays
    while (i < arr_size && j < val_insert_count)
    {
        if (array[i] < insert_array[j])
        {
            result[k] = array[i];
            i++;
            k++;
        } 
        else
        {
            result[k] = insert_array[j];
            j++;
            k++;        
        }
    }
    
    // Copy remaining elements
    while (i < arr_size)
        result[k++] = array[i++];
    
    while (j < val_insert_count)
        result[k++] = insert_array[j++];
    
    // Print result
    printf("\nMerged array: ");
    for (i = 0; i < k; i++)
        printf("%d ", result[i]);
    printf("\n");
    
    return 0;
}
